# Generated by Django 5.2.2 on 2025-09-29 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kan_mind_app', '0004_remove_task_assigne_id_remove_task_reviewer_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='kan_mind_app.board'),
        ),
    ]
