# Generated by Django 5.2.2 on 2025-09-30 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kan_mind_app', '0005_alter_task_board'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='assigne',
            new_name='assignee',
        ),
    ]
