# Generated by Django 5.2.2 on 2025-10-10 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kan_mind_app', '0009_alter_comment_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='kan_mind_app.board'),
        ),
    ]
