# Generated by Django 5.2.2 on 2025-10-13 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KanMind_app', '0011_task_creator'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_at']},
        ),
    ]
